sudo: false

language: node_js
node_js:
  - "6"

install: true
script: ./utils/deploy-docs.sh

env:
  global:
    - GITHUB_REPO: "sensebox/openSenseMap-API"
    - secure: "CZsR5GyWLgOpGDo3Yw622/oOjXJdJ8yJ3NEzQbyILqqfLCVnge9ee0/VIrevJB4rvI5Fhn0/pil3s8dGS9r6Ljg4PCao94By7M/o0gT6kkvMLFyTpwpJnPij0IYntO0kZVPMq8NYTM9VkfNawhnKginyTX1HJUsSmov6Oaz/ZlY="

branches:
  only:
    - master
