version: "2"
services:
  osem-api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./config/index.js:/usr/src/app/config/index.js
      - ./usersketches:/var/OpenSenseMap-API/usersketches
      - ./userimages:/var/www/OpenSenseMap/app/userimages
    env_file: .env
    depends_on:
      - db

  db:
    build:
      context: ./osem-mongo
    volumes:
      - ./mongo-data:/data/db
    env_file: .env
    command: --auth

