version: "2"
services:
  osem-api:
    build:
      context: .
      dockerfile: ./tests/Dockerfile
    volumes:
      - ./app.js:/usr/src/app/app.js
      - ./lib:/usr/src/app/lib
      - ./config/index.js:/usr/src/app/config/index.js
      - ./package.json:/usr/src/app/package.json
      - ./tests:/usr/src/app/tests
    env_file: .env
    environment:
      OSEM_targetFolder: ./usersketches
      OSEM_imageFolder: ./userimages
      OSEM_mailer_url: https://mailer:3924/
      OSEM_mailer_cert: |-
        -----BEGIN CERTIFICATE-----
        MIIDMTCCAhkCCQDVuxUPFKIyvzANBgkqhkiG9w0BAQsFADCBijEaMBgGCSqGSIb3
        DQEJARYLY2FAc2Vuc2Vib3gxCzAJBgNVBAYTAkRFMQwwCgYDVQQIDANOUlcxETAP
        BgNVBAcMCE11ZW5zdGVyMREwDwYDVQQKDAhzZW5zZUJveDEXMBUGA1UECwwOc2Vu
        c2VCb3hEZXZPcHMxEjAQBgNVBAMMCW1haWxlcl9jYTAeFw0xNjEyMzAwODM0MTJa
        Fw0yNjEyMjgwODM0MTJaMIGxMR4wHAYJKoZIhvcNAQkBFg9jbGllbnRAc2Vuc2Vi
        b3gxCzAJBgNVBAYTAkRFMQwwCgYDVQQIDANOUlcxETAPBgNVBAcMCE11ZW5zdGVy
        MREwDwYDVQQKDAhzZW5zZUJveDEXMBUGA1UECwwOc2Vuc2VCb3hEZXZPcHMxEjAQ
        BgNVBAMMCWxvY2FsaG9zdDEhMB8GA1UdEQwYRE5TLjE9YXBpLEROUy4yPW9zZW0t
        YXBpMIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQAqDTAbyghQlSckrSJkuTND7/P
        rbkHfBA9YWlp3/fv6uEyN/9SRxAEq+LJ2nekdhSqx34bxFCr1/DSJZFrNQC4LOUB
        ocqXktRSwvZtgzus/AMQ8nt+EyPCRzBpy+XNmpoCQT/xU8rm3NbZcZ0M8EX6tFsm
        CrLyP1pi4vkMTiJhTPt9Y4cwDQYJKoZIhvcNAQELBQADggEBAClSbeHy8HxFXgwT
        18I9Hzo3OPsNVj1/8vhIx8tKIc8qJe3UPXflAaqdjEe8/ND/LWgT33cuaAQBs2KD
        q5M2iVfoMU4G7AxJwLm6N3wDMvvNMmre0bNLR5lXsqWCWQnKYG6Ps+ZKq5wgBeBi
        SF6YoawfxH+XcGac3P9+PXqnXmWJRn8O3Eqh3wk7TpuMTUiqdM/uF5989BdZWBjJ
        ydqkPbmu6hX08ik7jeGpMBkSJne6hz9iffDFFwBZXlzNmcQVBiUlWd9yINNC+rkr
        qiNIBE2QCeefBbxdcm97pr2pKPzRurWW0+VAR3Ad8ln3jl88RYGUTd3UgfQ2jb9e
        2wumMXk=
        -----END CERTIFICATE-----
      OSEM_mailer_key: |-
        -----BEGIN EC PARAMETERS-----
        BgUrgQQAIw==
        -----END EC PARAMETERS-----
        -----BEGIN EC PRIVATE KEY-----
        MIHcAgEBBEIB2qLn+Do4fTQN4023uJMi4eiy4x4lO5lxtm9brqUVdzhOHSn4qUqB
        2SLMv6DzFXA0AAS+7snLiNN761JpfJdvwh2gBwYFK4EEACOhgYkDgYYABACoNMBv
        KCFCVJyStImS5M0Pv8+tuQd8ED1haWnf9+/q4TI3/1JHEASr4snad6R2FKrHfhvE
        UKvX8NIlkWs1ALgs5QGhypeS1FLC9m2DO6z8AxDye34TI8JHMGnL5c2amgJBP/FT
        yubc1tlxnQzwRfq0WyYKsvI/WmLi+QxOImFM+31jhw==
        -----END EC PRIVATE KEY-----
      OSEM_mailer_ca: |-
        -----BEGIN CERTIFICATE-----
        MIID6TCCAtGgAwIBAgIJAL7hoablklOwMA0GCSqGSIb3DQEBCwUAMIGKMRowGAYJ
        KoZIhvcNAQkBFgtjYUBzZW5zZWJveDELMAkGA1UEBhMCREUxDDAKBgNVBAgMA05S
        VzERMA8GA1UEBwwITXVlbnN0ZXIxETAPBgNVBAoMCHNlbnNlQm94MRcwFQYDVQQL
        DA5zZW5zZUJveERldk9wczESMBAGA1UEAwwJbWFpbGVyX2NhMB4XDTE2MTIzMDA4
        MzQwOVoXDTI2MTIyODA4MzQwOVowgYoxGjAYBgkqhkiG9w0BCQEWC2NhQHNlbnNl
        Ym94MQswCQYDVQQGEwJERTEMMAoGA1UECAwDTlJXMREwDwYDVQQHDAhNdWVuc3Rl
        cjERMA8GA1UECgwIc2Vuc2VCb3gxFzAVBgNVBAsMDnNlbnNlQm94RGV2T3BzMRIw
        EAYDVQQDDAltYWlsZXJfY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
        AQDOyz0v1OqOzzKDxG60SuVOx2n2CvaQ7VyDdrSmXo0U6qG2+VTi5deltLwkbv3G
        JpRxhkvTvqA/OJl8bQ5A4JjhXa+Kco1gQrO7eezTbqG7gj03YFXEaV4xtTeu9j5Y
        mstIdl7/kXgJXc9Irgner5wS4knRi+xxdUht4hrRx8Vt57mTg0Dtnfwugh454cPB
        tc1LwjsO+nNqHLVWtJQgGWrJ4wdGqd4PgC7XhEIVVyODTDI2xVN3GeElSmW+4ESW
        M45jg+Gis5YqK8PvUcfsNKP082+CqzBsgV8ML//E1sNWWsQWaVvF4cMpk91amy0E
        UdWks8WRzHRPCtMKYYTepiuJAgMBAAGjUDBOMB0GA1UdDgQWBBQenfio/O0taYDX
        Czm9ZNy2OQl1wDAfBgNVHSMEGDAWgBQenfio/O0taYDXCzm9ZNy2OQl1wDAMBgNV
        HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAsXQlavMMi6Lj9swoQPdTsdZ1B
        UaCrJvn6VDX2P+t4g86/I0X/6RPaUKCb/kGeOquXVSAY1bmHrbB4UdtwpkYbShqy
        aPoL42bJBhdne9jOn+k4mq3gOVo5lf26rmTnD3fXWaZTMZZdNy6rkjA2xBAgYEsm
        O73rEC+wp+EGfbYLR6WiiNp5z+yIhyIzTQRVWfCO5ms6z+XI9FNsCx3ieW28eu5n
        K9oxZ/4AclynvUWmbxL+vcPhyDzs7kQ0ns5GyxxVueQTqL+nRZXtjS1FbJFDnP/K
        xToAGiWD6F5duhs6IFH9Pfbtw/uOQ0zYoTMlSmsONv5GHLxxkGRBjLbr7LzE
        -----END CERTIFICATE-----
    depends_on:
      - db

  mailer:
    image: sensebox/sensebox-mailer
    environment:
      SENSEBOX_MAILER_SERVER_CERT: |-
        -----BEGIN CERTIFICATE-----
        MIIDOzCCAiMCCQDVuxUPFKIyvjANBgkqhkiG9w0BAQsFADCBijEaMBgGCSqGSIb3
        DQEJARYLY2FAc2Vuc2Vib3gxCzAJBgNVBAYTAkRFMQwwCgYDVQQIDANOUlcxETAP
        BgNVBAcMCE11ZW5zdGVyMREwDwYDVQQKDAhzZW5zZUJveDEXMBUGA1UECwwOc2Vu
        c2VCb3hEZXZPcHMxEjAQBgNVBAMMCW1haWxlcl9jYTAeFw0xNjEyMzAwODM0MTBa
        Fw0yNjEyMjgwODM0MTBaMIG7MR4wHAYJKoZIhvcNAQkBFg9zZXJ2ZXJAc2Vuc2Vi
        b3gxCzAJBgNVBAYTAkRFMQwwCgYDVQQIDANOUlcxETAPBgNVBAcMCE11ZW5zdGVy
        MREwDwYDVQQKDAhzZW5zZUJveDEXMBUGA1UECwwOc2Vuc2VCb3hEZXZPcHMxEjAQ
        BgNVBAMMCWxvY2FsaG9zdDErMCkGA1UdEQwiRE5TLjE9bWFpbGVyLEROUy4yPXNl
        bnNlYm94LW1haWxlcjCBmzAQBgcqhkjOPQIBBgUrgQQAIwOBhgAEAW9Hwci5Cx9b
        J4sOrnHa/kzKT/XfFadGSRnKWYNPipPzxc5Gl6TdY2a6u2CAV9G59MERLzpzA4N5
        Symrg3A0/WTiAaiN24UkDHwmTk8EhV3YoHWBvT6kbZ++5k+rSm0sOKPCzX4TlNjX
        WlK1cFNNP1r+nJyJ+qFfSfGMbp1+gfscsmGeMA0GCSqGSIb3DQEBCwUAA4IBAQCf
        5UL3WXtcSFybQRNAjAzx3d3tAd12Ozd0rRTNuVmrVeKogiAwlgicbMayzPMtSeHA
        nE3CL7PdESWD9KC7l/u3S+P8mAU+6kr1wT4Q+XsJFU0BOf7r/FghpBGmmBmZDCvk
        28eudtzElru0rNaayTaP9cnOV9+ruPMTTtgEFN/NQuEcYOCJT4DiJ64UGdxOFxWi
        RwaE6vKfBoFwbyAcrV9/TJFb8BK0Qu8AxUi80qPDHbPN3cU9z4ceo34TMiy+5VIF
        /v7Xi7bNz5sKff61TLAQqjiYVRk5pO+tyOl7pLNlUDrmq7ukVyNRr7nX0cWn4k5q
        wSIBIncw4acwrIU9Yaf3
        -----END CERTIFICATE-----
      SENSEBOX_MAILER_SERVER_KEY: |-
        -----BEGIN EC PARAMETERS-----
        BgUrgQQAIw==
        -----END EC PARAMETERS-----
        -----BEGIN EC PRIVATE KEY-----
        MIHcAgEBBEIBGqEr1XTt4bBy0xTGfSDPkLXshgkmAlU6x+WHjJtPULnl4RUhEtCC
        r+WZE8gTl76oqdSYPIlk1xw4XNsUbWI0brCgBwYFK4EEACOhgYkDgYYABAFvR8HI
        uQsfWyeLDq5x2v5Myk/13xWnRkkZylmDT4qT88XORpek3WNmurtggFfRufTBES86
        cwODeUspq4NwNP1k4gGojduFJAx8Jk5PBIVd2KB1gb0+pG2fvuZPq0ptLDijws1+
        E5TY11pStXBTTT9a/pycifqhX0nxjG6dfoH7HLJhng==
        -----END EC PRIVATE KEY-----
      SENSEBOX_MAILER_CA_CERT: |-
        -----BEGIN CERTIFICATE-----
        MIID6TCCAtGgAwIBAgIJAL7hoablklOwMA0GCSqGSIb3DQEBCwUAMIGKMRowGAYJ
        KoZIhvcNAQkBFgtjYUBzZW5zZWJveDELMAkGA1UEBhMCREUxDDAKBgNVBAgMA05S
        VzERMA8GA1UEBwwITXVlbnN0ZXIxETAPBgNVBAoMCHNlbnNlQm94MRcwFQYDVQQL
        DA5zZW5zZUJveERldk9wczESMBAGA1UEAwwJbWFpbGVyX2NhMB4XDTE2MTIzMDA4
        MzQwOVoXDTI2MTIyODA4MzQwOVowgYoxGjAYBgkqhkiG9w0BCQEWC2NhQHNlbnNl
        Ym94MQswCQYDVQQGEwJERTEMMAoGA1UECAwDTlJXMREwDwYDVQQHDAhNdWVuc3Rl
        cjERMA8GA1UECgwIc2Vuc2VCb3gxFzAVBgNVBAsMDnNlbnNlQm94RGV2T3BzMRIw
        EAYDVQQDDAltYWlsZXJfY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
        AQDOyz0v1OqOzzKDxG60SuVOx2n2CvaQ7VyDdrSmXo0U6qG2+VTi5deltLwkbv3G
        JpRxhkvTvqA/OJl8bQ5A4JjhXa+Kco1gQrO7eezTbqG7gj03YFXEaV4xtTeu9j5Y
        mstIdl7/kXgJXc9Irgner5wS4knRi+xxdUht4hrRx8Vt57mTg0Dtnfwugh454cPB
        tc1LwjsO+nNqHLVWtJQgGWrJ4wdGqd4PgC7XhEIVVyODTDI2xVN3GeElSmW+4ESW
        M45jg+Gis5YqK8PvUcfsNKP082+CqzBsgV8ML//E1sNWWsQWaVvF4cMpk91amy0E
        UdWks8WRzHRPCtMKYYTepiuJAgMBAAGjUDBOMB0GA1UdDgQWBBQenfio/O0taYDX
        Czm9ZNy2OQl1wDAfBgNVHSMEGDAWgBQenfio/O0taYDXCzm9ZNy2OQl1wDAMBgNV
        HRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAsXQlavMMi6Lj9swoQPdTsdZ1B
        UaCrJvn6VDX2P+t4g86/I0X/6RPaUKCb/kGeOquXVSAY1bmHrbB4UdtwpkYbShqy
        aPoL42bJBhdne9jOn+k4mq3gOVo5lf26rmTnD3fXWaZTMZZdNy6rkjA2xBAgYEsm
        O73rEC+wp+EGfbYLR6WiiNp5z+yIhyIzTQRVWfCO5ms6z+XI9FNsCx3ieW28eu5n
        K9oxZ/4AclynvUWmbxL+vcPhyDzs7kQ0ns5GyxxVueQTqL+nRZXtjS1FbJFDnP/K
        xToAGiWD6F5duhs6IFH9Pfbtw/uOQ0zYoTMlSmsONv5GHLxxkGRBjLbr7LzE
        -----END CERTIFICATE-----


  db:
    build:
      context: ./osem-mongo
    env_file: .env

